server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/${MYSQL_DB_NAME:crud_demo}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:Radixweb8}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
